apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data-pv
