apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql-cluster-ip:8888
            - name: WORDPRESS_DB_USER
              value: username
            - name: WORDPRESS_DB_PASSWORD
              value: userpassword
            - name: WORDPRESS_DB_NAME
              value: mysqldb
          ports:
            - containerPort: 80
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html
      volumes:
        - name: wordpress-data
          hostPath:
            path: /data
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  selector:
    app: wordpress
  type: NodePort
  ports:
    - nodePort: 30008
      port: 80
      #targetPort: 3306
