apiVersion: v1
kind: Service
metadata:
  name: service-nodeport-web
  namespace: production
spec:
  selector:
    app: web
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30008

